# Setting the format of the prompt
# format = """
# $username\
# $directory\
# $all\
# $character"""

format = """
$character \
$all
"""

right_format = """$cmd_duration"""

# Inserts a blank line between shell prompts
add_newline = false

# Making a single line prompt
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red) "

[package]
disabled = true

# Setting Icons for git status
[git_status]
style = "bold white"    
conflicted = "CONFLICT"
ahead = "↑"
behind = "↓"
diverged = "⇵"
up_to_date = ""
untracked = "??"    
disabled = false

# Setting time on the prompt

[time]
disabled = true
format = ' [\[ $time \]]($style) '
time_format = "%T"
#utc_time_offset = "-5"
time_range = "00:00:00-24:00:00"
use_12hr = false
style = "bold green"
#time = 10:03:16

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[hostname]
ssh_only = false
# format = "[$ssh_symbol](bold blue) on [$hostname](bold red) "
format = "[$hostname](bold red) "
# trim_at = ".companyname.com"
disabled = true

[username]
#style_user = "white bold"
style_user = "yellow bold"
style_root = "black bold"
format = "[$user]($style)@"
disabled = true
show_always = true

[git_branch]
symbol = " "
style = "bold italic red"
format = "[git:](bold blue)[\\(](bold blue)[$branch(:$remote_branch)]($style)[\\)](bold blue) "